<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyQuanCafe" Class="MasterDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-IODJG8F\SQLEXPRESS2012;Initial Catalog=QuanLyQuanCafe;Integrated Security=True" SettingsObjectName="DXApplication1.Properties.Settings" SettingsPropertyName="QuanLyQuanCafeConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.TrangThai" Member="TrangThais">
    <Type Name="TrangThai">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LOAI" Member="LOAIs">
    <Type Name="LOAI">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHAPKHO" Member="NHAPKHOs">
    <Type Name="NHAPKHO">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TienNhap" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.TaiKhoan" Member="TaiKhoans">
    <Type Name="TaiKhoan">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Pass" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MENU" Member="MENUs">
    <Type Name="MENU">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="LoaiID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.BAN" Member="BANs">
    <Type Name="BAN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HDID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HOADON" Member="HOADONs">
    <Type Name="HOADON">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayHD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BanID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDaLam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.CHITIETHOADON" Member="CHITIETHOADONs">
    <Type Name="CHITIETHOADON">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HDID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MenuID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DonGia" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsDaLam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BangCong" Member="BangCongs">
    <Type Name="BangCong">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BatDau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NVID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BangLuong" Member="BangLuongs">
    <Type Name="BangLuong">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NVID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLuong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDangLam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayNghiViec" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichSuTraLuong" Member="LichSuTraLuongs">
    <Type Name="LichSuTraLuong">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThangTra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NVID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TamUng" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ThucNhan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NamTra" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Insert_NhapKho" Method="Insert_NhapKho">
    <Parameter Name="NgayNhap" Parameter="ngayNhap" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="NVarChar(500)" />
    <Parameter Name="TienNhap" Parameter="tienNhap" Type="System.Decimal" DbType="Money" />
    <Parameter Name="MaNV" Parameter="maNV" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Menu_Select" Method="Menu_Select">
    <ElementType Name="Menu_SelectResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="LoaiID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HinhAnh" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NhapKho_Select" Method="NhapKho_Select">
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="MaNV" Parameter="maNV" Type="System.Int32" DbType="Int" />
    <ElementType Name="NhapKho_SelectResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayNhap" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="TienNhap" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Sender" Type="System.String" DbType="NVarChar(8) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.BaoCao_Select" Method="BaoCao_Select">
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="BaoCao_SelectResult">
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="LoaiID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NgayHD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UserID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CTHD_Select" Method="CTHD_Select">
    <Parameter Name="HDID" Parameter="hDID" Type="System.Int32" DbType="Int" />
    <ElementType Name="CTHD_SelectResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.String" DbType="NVarChar(73)" CanBeNull="true" />
      <Column Name="SL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="LoaiID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Ban_Select" Method="Ban_Select">
    <ElementType Name="Ban_SelectResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HDID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(54)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Update_HD2" Method="Update_HD2">
    <Parameter Name="HDID" Parameter="hDID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Parameter Name="IDCu" Parameter="iDCu" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Update_HD3" Method="Update_HD3">
    <Parameter Name="HDID" Parameter="hDID" Type="System.Int32" DbType="Int" />
    <Parameter Name="HDIDCu" Parameter="hDIDCu" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CTHD_Select2" Method="CTHD_Select2">
    <Parameter Name="HDID" Parameter="hDID" Type="System.Int32" DbType="Int" />
    <ElementType Name="CTHD_Select2Result">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TenMon" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.String" DbType="NVarChar(73)" CanBeNull="true" />
      <Column Name="SL" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaBan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="LoaiID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.DSCho_Select" Method="DSCho_Select">
    <ElementType Name="DSCho_SelectResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Number" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MaTT" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HDID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(54)" CanBeNull="true" />
      <Column Name="NgayHD" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Update_HD" Method="Update_HD">
    <Parameter Name="HDID" Parameter="hDID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.BaoCaoChart_Select" Method="BaoCaoChart_Select">
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="BaoCaoChart_SelectResult">
      <Column Name="NgayHD" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BaoCaoChartNam_Select" Method="BaoCaoChartNam_Select">
    <Parameter Name="TuNam" Parameter="tuNam" Type="System.Int32" DbType="Int" />
    <Parameter Name="DenNam" Parameter="denNam" Type="System.Int32" DbType="Int" />
    <ElementType Name="BaoCaoChartNam_SelectResult">
      <Column Name="NgayHD" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BaoCaoChartThang_Select" Method="BaoCaoChartThang_Select">
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <ElementType Name="BaoCaoChartThang_SelectResult">
      <Column Name="NgayHD" Type="System.String" DbType="NVarChar(7)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BaoCaoChartQuy_Select" Method="BaoCaoChartQuy_Select">
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <ElementType Name="BaoCaoChartQuy_SelectResult">
      <Column Name="NgayHD" Type="System.String" DbType="NVarChar(4)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BaoCaoChartBanChay_Select" Method="BaoCaoChartBanChay_Select">
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="DenNgay" Parameter="denNgay" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="BaoCaoChartBanChay_SelectResult">
      <Column Name="NgayHD" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.NhanVien_Select" Method="NhanVien_Select">
    <ElementType Name="NhanVien_SelectResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDangLam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayNghiViec" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CachTinhLuong" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LichSuDiLam_Select" Method="LichSuDiLam_Select">
    <Parameter Name="NVID" Parameter="nVID" Type="System.Int32" DbType="Int" />
    <ElementType Name="LichSuDiLam_SelectResult">
      <Column Name="NgayLam" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BatDau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NVID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="GioLam" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LichSuTamUng_Select" Method="LichSuTamUng_Select">
    <Parameter Name="NVID" Parameter="nVID" Type="System.Int32" DbType="Int" />
    <ElementType Name="LichSuTamUng_SelectResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NVID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLuong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LichSuDiLam2_Select" Method="LichSuDiLam2_Select">
    <Parameter Name="NVID" Parameter="nVID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="LichSuDiLam2_SelectResult">
      <Column Name="NgayLam" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BatDau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NVID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="KetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ID1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Age" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="MucLuong" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="DonViTinh" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsDangLam" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="NgayVaoLam" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayNghiViec" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GioLam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TienLuong" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LichSuTamUng2_Select" Method="LichSuTamUng2_Select">
    <Parameter Name="NVID" Parameter="nVID" Type="System.Int32" DbType="Int" />
    <Parameter Name="TuNgay" Parameter="tuNgay" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="LichSuTamUng2_SelectResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NVID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NgayLuong" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.LichSuTraLuong_Select" Method="LichSuTraLuong_Select">
    <Parameter Name="NVID" Parameter="nVID" Type="System.Int32" DbType="Int" />
    <ElementType Name="LichSuTraLuong_SelectResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NgayTra" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ThangTra" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SoTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="NVID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TamUng" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="ThucNhan" Type="System.Decimal" DbType="Money" CanBeNull="true" />
      <Column Name="GhiChu" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="NamTra" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BaoCaoChartLoiNhuanNam_Select" Method="BaoCaoChartLoiNhuanNam_Select">
    <Parameter Name="TuNam" Parameter="tuNam" Type="System.Int32" DbType="Int" />
    <Parameter Name="DenNam" Parameter="denNam" Type="System.Int32" DbType="Int" />
    <ElementType Name="BaoCaoChartLoiNhuanNam_SelectResult">
      <Column Name="NgayHD" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.BaoCaoChartLoiNhuanThang_Select" Method="BaoCaoChartLoiNhuanThang_Select">
    <Parameter Name="Nam" Parameter="nam" Type="System.Int32" DbType="Int" />
    <ElementType Name="BaoCaoChartLoiNhuanThang_SelectResult">
      <Column Name="NgayHD" Type="System.String" DbType="NVarChar(8)" CanBeNull="true" />
      <Column Name="ThanhTien" Type="System.Decimal" DbType="Money" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>